---
- hosts: localhost
  connection: local
  name: Update and install tools for TLS
  become: true
  pre_tasks:
  - name: update repository index
    apt:
      update_cache: yes
    changed_when: false
  - name: install basic tools
    apt:
      name: ["curl", "gpg", "ca-certificates"]
      state: latest

- hosts: localhost
  connection: local
  name: Set up
  become: true
  vars_files:
    - vars/main.yaml
    - vars/users.yaml
  tasks:
    - import_tasks: tasks/repositories.yaml
    - import_tasks: tasks/install.yaml
    - import_tasks: tasks/users.yaml
    - import_tasks: tasks/acer.yaml

- hosts: localhost
  connection: local
  name: Set Up environment
  become: yes
  become_user: jan
  tasks:
    - import_tasks: tasks/env.yaml
