---
- name: update cahce
  apt:
    update_cache: yes

- name: install base tools TUI
  loop: [
      "ca-certificates", "curl", "gnupg",
		  "git", "tig", "tmux", "nmap", "mc", "wget", "terminator", "htop", "tar", "zip", "unzip", "htop", "stow",
		  "sudo", "ssh", "net-tools",
		  "gcc", "g++", "python3", "python3-pip", "make", "cmake",
		  "docker-ce", "docker-ce-cli", "containerd.io", "docker-compose-plugin",
		  "vim", "nano", "less",
  		"snapd"
    ]
  apt:
    name: "{{item}}"
    state: latest
    install_recommends: no

- name: install base tools GUI
  tags: never, gui
  loop: ["gnome-core", "network-manager", "terminator", "vlc", "gnome-tweaks", "google-chrome-stable", "code"]
  apt:
    name: "{{item}}"
    state: latest
    install_recommends: no
